# this container should be prepared for golang
language: go
go: 
 - 1.10

install:
 - go get github.com/axw/gocov/...
 - go get github.com/AlekSi/gocov-xml

script:
 - gocov test ./... | gocov-xml > coverage.xml
