version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ADD_PUBLIC_IP_ADDRESS
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  argo-messaging:
    build: .
    ports:
      - "443:8080"
    depends_on:
        - mongo
        - kafka
    links:
      - mongo
      - zookeeper
      - kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
