# ARGO Messaging API expressed in swagger
swagger: '2.0'
info:
  title: argo-messaging-api
  description: "ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures. This swagger UI interface provides access to the specification of the ARGO messaging api, which can be used to produce or consume messages."
  version: "0.9.2"
  contact:
    name: ARGO Developers
    url: http://argoeu.github.io/
    email: argo-dev@lists.grnet.gr

host: localhost
schemes:
  - https

basePath: /v1
produces:
  - application/json
tags:
  - name: Subscriptions
    description: Subscriptions under a given project
  - name: Topics
    description: Topics under a given project
paths:
  /projects/{PROJECT}/subscriptions:
    get:
      summary: List subscriptions in a project
      description: |
        The subscriptions endpoint returns a list of available subscriptions for a given project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
      tags:
        - Subscriptions
      responses:
        200:
          description: An array of subscriptions
          schema:
            type: array
            items:
              $ref: '#/definitions/Subscription'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

  /projects/{PROJECT}/subscriptions/{SUBSCRIPTION}:
    get:
      summary: Show infromation about a specific subscription
      description: |
        Lists information about a specific subscription belonging to a specific project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the subscription
          required: true
          type: string
      tags:
        - Subscriptions
      responses:
        200:
          description: An array of Subscriptions
          schema:
            $ref: '#/definitions/Subscription'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      summary: Create a new subscription in a project
      description: |
        This request creates a new subscription in a project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the topic
          required: true
          type: string
        - name: parameters
          in: body
          description: Parameters of the new subscription object
          required: true
          schema:
           $ref: '#/definitions/SubParameters'
      tags:
        - Subscriptions
      responses:
        200:
          description: The new subscription object created
          schema:
            $ref: '#/definitions/Subscription'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        409:
          $ref: "#/responses/409"
        500:
          $ref: "#/responses/500"

    delete:
      summary: Delete an existing subscription in a project
      description: |
        This request deletes an existing subscription in a project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the subscription
          required: true
          type: string
      tags:
        - Subscriptions
      responses:
        200:
          description: Empty response if the subscription is successfully deleted
          schema:
            type: string
            default: ""
            description: empty string
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        409:
          $ref: "#/responses/409"
        500:
          $ref: "#/responses/500"



  /projects/{PROJECT}/subscriptions/{SUBSCRIPTION}:pull:
    post:
      summary: Pull Messages from an existing subscription
      description: |
        Use an existing subscription to pull messages
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the subscription
          required: true
          type: string
        - name: Pull Options
          in: body
          description: Parameters to be used during pull
          required: true
          schema:
           $ref: '#/definitions/PullOptions'
      tags:
        - Subscriptions
      responses:
        200:
          description: An array of received messages
          schema:
            $ref: '#/definitions/ReceivedMessages'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

  /projects/{PROJECT}/subscriptions/{SUBSCRIPTION}:acknowledge:
    post:
      summary: Acknowledge the succesfull delivery of pulled messages
      description: |
        Use ackId to inform the api that the messages have been correctly received
      parameters:
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the subscription
          required: true
          type: string
        - name: Ack Options
          in: body
          description: Parameters to be used during acknowledgement
          required: true
          schema:
           $ref: '#/definitions/AckIDs'
      tags:
        - Subscriptions
      responses:
        200:
          description: An array of received messages
          schema:
            $ref: '#/definitions/ReceivedMessages'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        408:
          $ref: "#/responses/408"
        500:
          $ref: "#/responses/500"

  /projects/{PROJECT}/subscriptions/{SUBSCRIPTION}:modifyPushConfig:
    post:
      summary: Modify the push configuration options of the subscription
      description: |
        Updating push configuration with push endpoint information results into changing the subscription to push mode. Updating push configuration to be empty results into changing the subscription to pull mode
      parameters:
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: SUBSCRIPTION
          in: path
          description: Name of the subscription
          required: true
          type: string
        - name: Push Configuration Options
          in: body
          description: Parameters to be used during acknowledgement
          required: true
          schema:
           $ref: '#/definitions/PushConfigRef'
      tags:
        - Subscriptions
      responses:
        200:
          description: Empty response if successful
          schema:
            type: string
            default: ""
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        408:
          $ref: "#/responses/408"
        500:
          $ref: "#/responses/500"

  /projects/{PROJECT}/topics:
    get:
      summary: List topics in a project
      description: |
        The Topics endpoint returns a list of available topics for a given project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: An array of topics
          schema:
            type: array
            items:
              $ref: '#/definitions/Topic'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

  /projects/{PROJECT}/topics/{TOPIC}:

    get:
      summary: List topics in a project
      description: |
        The Topics endpoint returns a list of available topics for a given project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: A topic object
          schema:
            $ref: '#/definitions/Topic'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      summary: Create a new topic in a project
      description: |
        This request creates a new topic in a project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: The new topic object created
          schema:
            $ref: '#/definitions/Topic'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        409:
          $ref: "#/responses/409"
        500:
          $ref: "#/responses/500"

    delete:
      summary: Delete an existing topic in a project
      description: |
        This request deletes an existing topic in a project
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: Empty response if the topic is successfully deleted
          schema:
            type: string
            default: ""
            description: empty string
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        409:
          $ref: "#/responses/409"
        500:
          $ref: "#/responses/500"



  /projects/{PROJECT}/topics/{TOPIC}:publish:
    post:
      summary: List topics in a project
      description: |
        The topic:publish endpoint publish a message to a specific topic
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
        - name: Messages
          in: body
          description: Message JSON representation
          required: true
          schema:
           $ref: '#/definitions/Messages'
      tags:
        - Topics
      responses:
        200:
          description: An array of messageIDs
          schema:
            $ref: '#/definitions/MessageIDs'
        400:
          $ref: "#/responses/400"
        401:
          $ref: "#/responses/401"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

parameters:
  ApiKey:
    name: key
    in: query
    description: user key token for authentication
    required: true
    type: string
    default: SecretKey123

responses:
  400:
    description: Invalid argument used
    schema:
      $ref: '#/definitions/ErrorMsg'
  401:
    description: Unauthorized user based on key
    schema:
      $ref: '#/definitions/ErrorMsg'
  403:
    description: Access Forbidden for the user on the resource
    schema:
      $ref: '#/definitions/ErrorMsg'
  404:
    description: Item not found
    schema:
      $ref: '#/definitions/ErrorMsg'
  408:
    description: Server timed out waiting for the request
    schema:
      $ref: '#/definitions/ErrorMsg'
  409:
    description: Item already exists!
    schema:
      $ref: '#/definitions/ErrorMsg'
  500:
    description: Internal Error
    schema:
      $ref: '#/definitions/ErrorMsg'

definitions:
  PullOptions:
    type: object
    properties:
      maxMessages:
        type: string
        description: Max number of messages to be consumed
  SubParameters:
    type: object
    properties:
      topic:
        type: string
        description: name of the topic this subscription will subscribe to
  Subscription:
    type: object
    properties:
      name:
        type: string
        description: Name of the subscription
      topic:
        type: string
        description: Name of the topic
      pushConfig:
            $ref: '#/definitions/PushConfig'
      ackDeadlineSeconds:
        type: integer
        description: maximum wait time in seconds for Acknowledgement
  PushConfigRef:
    type: object
    properties:
      pushConfig:
         $ref: '#/definitions/PushConfig'
  PushConfig:
    type: object
    properties:
      pushEndpoint:
        type: string
        description: endpoint url for endpoint to push messages
  Topic:
    type: object
    properties:
      name:
        type: string
        description: Name of the topic
  Attribute:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Message:
    type: object
    properties:
      attributes:
        type: array
        items:
          $ref: '#/definitions/Attribute'
      data:
        type: string
        description: Message payload in Base64 encoding"
  Messages:
    type: array
    items:
      $ref: '#/definitions/Message'
  ReceivedMessages:
    type: object
    properties:
      receivedMessages:
        type: array
        items:
          $ref: '#/definitions/ReceivedMessage'
  ReceivedMessage:
    type: object
    properties:
      ackId:
        type: string
        description: AckId to be used in acknowledge request
      message:
        type: object
        properties:
          messageId:
            type: string
            description: id of the message
          attributes:
            type: array
            description: key/value dictionary accompanying the message
            items:
              $ref: '#/definitions/Attribute'
          data:
            type: string
            description: base64 encoding of the message payload
          publishTime:
            type: string
            description: publish datetime in ISO8601 string (+ns)


  MessageIDs:
     type: object
     properties:
       messageIds:
         type: array
         items:
           type: string

  AckIDs:
     type: object
     properties:
       ackIds:
         type: array
         items:
           type: string

  ErrorMsg:
    type: object
    properties:
      error:
        type: object
        properties:
          code:
            type: string
            description: code of the error
          message:
            type: string
            description: general message of the error
          status:
            type: string
            description: status of the error
