# ARGO Messaging API expressed in swagger
swagger: '2.0'
info:
  title: argo-messaging-api
  description:  ARGO Messaging API for broker network
  version: "0.9.1-1"

host: localhost
schemes:
  - http

basePath: /v1
produces:
  - application/json
paths:
  /projects/{PROJECT}/topics:
    get:
      summary: List topics in a project
      description: |
        The Topics endpoint returns a list of available topics for a given project
      parameters:
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: An array of topics
          schema:
            type: array
            items:
              $ref: '#/definitions/Topic'

  /projects/{PROJECT}/topics/{TOPIC}:
    get:
      summary: List topics in a project
      description: |
        The Topics endpoint returns a list of available topics for a given project
      parameters:
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
      tags:
        - Topics
      responses:
        200:
          description: An array of topics
          schema:
            $ref: '#/definitions/Topic'
  /projects/{PROJECT}/topics/{TOPIC}:publish:
    get:
      summary: List topics in a project
      description: |
        The topic:publish endpoint publish a message to a specific topic
      parameters:
        - name: PROJECT
          in: path
          description: Name of the project
          required: true
          type: string
        - name: TOPIC
          in: path
          description: Name of the topic
          required: true
          type: string
        - name: Message
          in: body
          description: Message JSON representation
          required: true
          schema:
           $ref: '#/definitions/Message'
      tags:
        - Topics
      responses:
        200:
          description: An array of messageIDs
          schema:
            $ref: '#/definitions/MessageIDs'

definitions:
  Topic:
    type: object
    properties:
      name:
        type: string
        description: Name of the topic
  Attribute:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Message:
    type: object
    properties:
      attributes:
        type: array
        items:
          $ref: '#/definitions/Attribute'
      data:
        type: string
        description: Message payload in Base64 encoding"
  MessageIDs:
     type: object
     properties:
       messageIDs:
         type: array
         items:
           type: string
