site_name: AMS documentation [V1]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/argo-messaging
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2016 GRNET S.A.


pages:
- Basic Information:
    - Overview and Introduction: 'overview.md'
    - Messaging Backend - Apache Kafka: msg_backend.md
    - Messaging API flow: msg_flow.md
    - Authentication & Authorization: auth.md
    - Project & User management guide: projects_users.md
- How to Guides:
    - Publisher Guide: publisher.md
    - Consumer Guide: consumer.md
- API Messaging API:
    - API Basic Information: api_basic.md
    - API Error Messages: api_errors.md
- API & References: 
    - API Authentication: api_auth.md
    - API Users: api_users.md
    - API Projects: api_projects.md
    - API Topics: api_topics.md
    - API Subscriptions: api_subs.md
    - API Operational Metrics: api_metrics.md
    - API Schemas: api_schemas.md
    - API Error Messages: api_errors.md
- Q&A:
    - General : qa_general_questions.md
    - Ruby : qa_ruby.md
theme: readthedocs
