site_name: Messaging Api documentation [V1]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/argo-messaging
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2015 GRNET S.A.

pages:
  - Home: index.md
  - Overview and Introduction: verview.md
  - Messaging Backend - Apache Kafkam: msg_backend.md
  - Messaging API flow: msg_flow.md
  - Authentication & Authorization: auth.md
  - Basic Information: api_basic.md
  - API Error Messages: api_errors.md
  - Auth related: api_auth.md
  - Topics related: api_topics.md
  - Subscriptions related: api_subs.md

theme: readthedocs



