site_name: Messaging Service documentation [V1]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/argo-messaging
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2015 GRNET S.A.

pages:
  - Home: index.md
  - Overview and Introduction: overview.md
  - Messaging Backend - Apache Kafka: msg_backend.md
  - Messaging API flow: msg_flow.md
  - Authentication & Authorization: auth.md
  - Publisher Guide: publisher.md
#  - Consumer Guide: consumer.md
  - API Basic Information: api_basic.md
  - API Authentication: api_auth.md
  - API Topics: api_topics.md
  - API Subscriptions: api_subs.md
  - API Error Messages: api_errors.md
theme: readthedocs



