name: CVE Tests
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
jobs:
  # This is to check the
  cve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
