name: Staticcheck

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  staticcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
